# Generated by Django 5.2.6 on 2025-09-20 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtstart', models.DateTimeField(blank=True, null=True)),
                ('dtend', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.BooleanField(choices=[(True, 'Inclusion'), (False, 'Exclusion')], default=True)),
                ('dt', models.DateTimeField()),
                ('recurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='recurrence.recurrence')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.BooleanField(choices=[(True, 'Inclusion'), (False, 'Exclusion')], default=True)),
                ('freq', models.PositiveIntegerField(choices=[(6, 'Secondly'), (5, 'Minutely'), (4, 'Hourly'), (3, 'Daily'), (2, 'Weekly'), (1, 'Monthly'), (0, 'Yearly')])),
                ('interval', models.PositiveIntegerField(default=1)),
                ('wkst', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('recurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='recurrence.recurrence')),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=16)),
                ('value', models.IntegerField()),
                ('index', models.IntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='recurrence.rule')),
            ],
        ),
    ]
